/*
 * Pizza API
 * Assignment 6 Pizza Ordering
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * Pizza
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2021-05-12T12:35:58.127Z")
public class Pizza {
  @SerializedName("pizza_id")
  private Integer pizzaId = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("vegetarian")
  private Boolean vegetarian = null;

  @SerializedName("price")
  private Double price = null;

  @SerializedName("toppings")
  private List<String> toppings = new ArrayList<String>();

  public Pizza pizzaId(Integer pizzaId) {
    this.pizzaId = pizzaId;
    return this;
  }

   /**
   * Get pizzaId
   * @return pizzaId
  **/
  @ApiModelProperty(example = "0", required = true, value = "")
  public Integer getPizzaId() {
    return pizzaId;
  }

  public void setPizzaId(Integer pizzaId) {
    this.pizzaId = pizzaId;
  }

  public Pizza name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(example = "margarita", required = true, value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public Pizza vegetarian(Boolean vegetarian) {
    this.vegetarian = vegetarian;
    return this;
  }

   /**
   * Get vegetarian
   * @return vegetarian
  **/
  @ApiModelProperty(example = "true", required = true, value = "")
  public Boolean isVegetarian() {
    return vegetarian;
  }

  public void setVegetarian(Boolean vegetarian) {
    this.vegetarian = vegetarian;
  }

  public Pizza price(Double price) {
    this.price = price;
    return this;
  }

   /**
   * Get price
   * @return price
  **/
  @ApiModelProperty(example = "12.5", required = true, value = "")
  public Double getPrice() {
    return price;
  }

  public void setPrice(Double price) {
    this.price = price;
  }

  public Pizza toppings(List<String> toppings) {
    this.toppings = toppings;
    return this;
  }

  public Pizza addToppingsItem(String toppingsItem) {
    this.toppings.add(toppingsItem);
    return this;
  }

   /**
   * Get toppings
   * @return toppings
  **/
  @ApiModelProperty(example = "[\"Mozzarella\",\"Tomatoes\",\"Basil\"]", required = true, value = "")
  public List<String> getToppings() {
    return toppings;
  }

  public void setToppings(List<String> toppings) {
    this.toppings = toppings;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Pizza pizza = (Pizza) o;
    return Objects.equals(this.pizzaId, pizza.pizzaId) &&
        Objects.equals(this.name, pizza.name) &&
        Objects.equals(this.vegetarian, pizza.vegetarian) &&
        Objects.equals(this.price, pizza.price) &&
        Objects.equals(this.toppings, pizza.toppings);
  }

  @Override
  public int hashCode() {
    return Objects.hash(pizzaId, name, vegetarian, price, toppings);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Pizza {\n");
    
    sb.append("    pizzaId: ").append(toIndentedString(pizzaId)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    vegetarian: ").append(toIndentedString(vegetarian)).append("\n");
    sb.append("    price: ").append(toIndentedString(price)).append("\n");
    sb.append("    toppings: ").append(toIndentedString(toppings)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

