/*
 * Pizza API
 * Assignment 6 Pizza Ordering
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.Order;
import java.io.IOException;
import org.threeten.bp.OffsetDateTime;

/**
 * SuccesfulOrder
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2021-05-12T12:35:58.127Z")
public class SuccesfulOrder {
  @SerializedName("order")
  private Order order = null;

  @SerializedName("ordered_at")
  private OffsetDateTime orderedAt = null;

  @SerializedName("delivery_time")
  private OffsetDateTime deliveryTime = null;

  public SuccesfulOrder order(Order order) {
    this.order = order;
    return this;
  }

   /**
   * Get order
   * @return order
  **/
  @ApiModelProperty(required = true, value = "")
  public Order getOrder() {
    return order;
  }

  public void setOrder(Order order) {
    this.order = order;
  }

  public SuccesfulOrder orderedAt(OffsetDateTime orderedAt) {
    this.orderedAt = orderedAt;
    return this;
  }

   /**
   * Get orderedAt
   * @return orderedAt
  **/
  @ApiModelProperty(example = "2012-04-23T18:05:32.511Z", required = true, value = "")
  public OffsetDateTime getOrderedAt() {
    return orderedAt;
  }

  public void setOrderedAt(OffsetDateTime orderedAt) {
    this.orderedAt = orderedAt;
  }

  public SuccesfulOrder deliveryTime(OffsetDateTime deliveryTime) {
    this.deliveryTime = deliveryTime;
    return this;
  }

   /**
   * Get deliveryTime
   * @return deliveryTime
  **/
  @ApiModelProperty(example = "2012-04-23T18:25:43.511Z", required = true, value = "")
  public OffsetDateTime getDeliveryTime() {
    return deliveryTime;
  }

  public void setDeliveryTime(OffsetDateTime deliveryTime) {
    this.deliveryTime = deliveryTime;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SuccesfulOrder succesfulOrder = (SuccesfulOrder) o;
    return Objects.equals(this.order, succesfulOrder.order) &&
        Objects.equals(this.orderedAt, succesfulOrder.orderedAt) &&
        Objects.equals(this.deliveryTime, succesfulOrder.deliveryTime);
  }

  @Override
  public int hashCode() {
    return Objects.hash(order, orderedAt, deliveryTime);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SuccesfulOrder {\n");
    
    sb.append("    order: ").append(toIndentedString(order)).append("\n");
    sb.append("    orderedAt: ").append(toIndentedString(orderedAt)).append("\n");
    sb.append("    deliveryTime: ").append(toIndentedString(deliveryTime)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

