version: "3.7"

services:

  pizza-postgres:
    container_name: pizza-postgres
    image: postgres:latest
    restart: always
    volumes:
      - ~/data/postgres:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
      - database.env
    ports:
      - 5432:5432


  pizza-server:
    container_name: pizza-server
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file:
      - database.env
    ports:
      - 8080:8080
    depends_on:
      - pizza-postgres