/*
 * Pizza API
 * Assignment 6 Pizza Ordering
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.Pizza;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for PizzaApi
 */
@Ignore
public class PizzaApiTest {

    private final PizzaApi api = new PizzaApi();

    
    /**
     * 
     *
     * Returns all pizzas that the restaurant offers.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void pizzaGetTest() throws ApiException {
        List<Pizza> response = api.pizzaGet();

        // TODO: test validations
    }
    
    /**
     * 
     *
     * Find a pizza by ID (return toppings in pizza, price and if it is vegetarian or not).
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void pizzaPizzaIdGetTest() throws ApiException {
        Integer pizzaId = null;
        Pizza response = api.pizzaPizzaIdGet(pizzaId);

        // TODO: test validations
    }
    
}
